# Generated by Django 4.0 on 2022-01-13 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0005_alter_receita_pesso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='pesso',
            new_name='pessoa',
        ),
    ]
